name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
     
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
     
      - name: Coverage report
        env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
          pip install coverage
          coverage run manage.py test --settings=core.settings.testing
          coverage report
      
     

      - name: Django Testing
        env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
          python manage.py test --settings=core.settings.testing